### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by benjaminpreiss** [Lilypad-Tech/web-ui#74]
We want to make this repo public.

Prerequisites:

- [ ] The API endpoints need auth: https://github.com/Lilypad-Tech/api/issues/83
- [ ] Establish contribution standards and enforce them
- [ ] Document development in README. (#88 )
- [x] Add pull request template (#85)
- [x] Add license (#83)
- [x] Add code of conduct (#84)
- [x] Add security policy
- [ ] Add issue templates

---

Co-authored by @bgins
